# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d2af4a5e9b3ff89674c1183c55500c3ceccf0dbc518d680c0adca6f083197a4bdc8a6c20a2b8f2f4628c705119032dd88cd6da82c9101a02098c507cbd315d2

test:
  secret_key_base: 950ba8d14d4139083c75cbfbcb8e45c4126b606ea13351037249082437e20dc969692cb3b88ad824add78c7027f41628004ce0c40103000349ea959eafc24da0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
